### ISSUE TITLE
Feed test failing on some chapters

### ISSUE THREAD

**Issue by colinmahns** [dsa-ntc/dsa-planet#5]
Need to dig in to this alert, continual failure running the test action for the various RSS feeds

Appears to be a mix of SSL errors and some chapter feeds just not being formatted correctly 

```Run docker://ruby:3.1
/usr/bin/docker run --name ruby31_5a435e --label ef7d85 --workdir /github/workspace --rm -e "BUNDLE_PATH" -e "LANG" -e "LANGUAGE" -e "LC_ALL" -e "INPUT_ENTRYPOINT" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "bundle" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dsa-planet/dsa-planet":"/github/workspace" ruby:3.1 exec rake test
/usr/local/bin/ruby tests/feedcheck.rb
/usr/local/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=162.255.118.65:443 state=error: certificate verify failed (certificate has expired) (Faraday::SSLError)
	from /usr/local/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:1089:in `connect'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:995:in `do_start'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:984:in `start'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:102:in `perform_request'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:66:in `block in call'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/adapter.rb:45:in `connection'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:65:in `call'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/request/url_encoded.rb:25:in `call'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/rack_builder.rb:153:in `build_response'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:444:in `run_request'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:200:in `get'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday.rb:145:in `method_missing'
	from tests/feedcheck.rb:37:in `block (2 levels) in <main>'
	from tests/feedcheck.rb:36:in `each'
	from tests/feedcheck.rb:36:in `block in <main>'
	from tests/feedcheck.rb:13:in `each'
	from tests/feedcheck.rb:13:in `<main>'
/usr/local/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=162.255.118.65:443 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
	from /usr/local/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:1089:in `connect'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:995:in `do_start'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:984:in `start'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:102:in `perform_request'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:66:in `block in call'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/adapter.rb:45:in `connection'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:65:in `call'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/request/url_encoded.rb:25:in `call'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/rack_builder.rb:153:in `build_response'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:444:in `run_request'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:200:in `get'
	from /github/workspace/.bundle/ruby/3.1.0/gems/faraday-2.7.10/lib/faraday.rb:145:in `method_missing'
	from tests/feedcheck.rb:37:in `block (2 levels) in <main>'
	from tests/feedcheck.rb:36:in `each'
	from tests/feedcheck.rb:36:in `block in <main>'
	from tests/feedcheck.rb:13:in `each'
	from tests/feedcheck.rb:13:in `<main>'
WARN: line 694 - duplicate key >title< in section; will overwrite existing value
:: akrondsa =>  ✓ ✓ ✓ 
:: athensareadsa =>  ✓ ✓ ✓ 
:: atlantadsa =>  ✓ ✓ ✓ 
:: berkshiresdsa =>  ✓ ✓ ✓ 
:: boisedsa =>  ✓ ✓ ✓ 
:: bostondsapoliticaleducationwg =>  ✓ ✓ ✓ 
:: bozemandsa =>  ✓ ✓ ✓ 
:: browardcountydsa =>  ✓ ✓ ✓ 
:: buffalodsa =>  ✓ ✓ ✓ 
:: centralarkansasdsa =>  ✓ ✓ ✓ 
:: centralindianadsa =>  ✓ ✓ ✓ 
:: centralnjdsa =>  ✓ ✓ ✓ 
:: centralvtdsa =>  ✓ ✓ ✓ 
:: champlainvalleydsa =>  ✓ ✓ ✓ 
rake aborted!
Command failed with status (1): [/usr/local/bin/ruby tests/feedcheck.rb...]
/github/workspace/Rakefile:11:in `block in <top (required)>'
/github/workspace/.bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/github/workspace/.bundle/ruby/3.1.0/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
:: charlestondsa =>  ✓ ```

**Comment by bmos** [comment]
So ideally:

- [ ] Skip/allow SSL errors in the test
- [ ] Making the feed syntax more permissive

Does this sound right?

**Comment by bmos** [comment]
I also emailed Charleston DSA to let them know about the SSL cert and also directed them to the NTC chapter websites subcommittee if they are struggling to maintain the cert and such.
